import type { Metadata } from "next";
import { Space_Grotesk, Inter } from "next/font/google";
import "./globals.css";

const grotesk = Space_Grotesk({
	weight: ["700"],
	subsets: ["latin"],
	variable: "--font-brand",
});

const inter = Inter({
	weight: ["400", "700"],
	subsets: ["latin"],
	variable: "--font-body",
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	// bg-gradient-to-br from-[var(--background)] to-[#b9b6ab]

	return (
		<html lang="en">
			<body
				className={`${grotesk.variable} ${inter.variable} antialiased bg-[var(--background)] text-[var(--foreground)]`}
			>
				{children}
			</body>
		</html>
	);
}
